language: node_js

node_js:
  - "node"  # latest stable release
  - "lts/*" # latest LTS release

script:
  - npm run lint
  - npm run test:cover

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token: 2d489d69b636c6f2f55bcbd103df3ced18bec35f0b57de1a4cdb2102094be833
